import { Globe } from "lucide-react";
import { SubjectPageTemplate, SubjectConfig } from "./SubjectPageTemplate";

const config: SubjectConfig = {
  lsKey: "ilim_english_progress",
  name: "Английский язык",
  nameKY: "Англис тили",
  emoji: "🇬🇧",
  Icon: Globe,
  headerGradient: "from-red-600 to-red-800",
  topics: [
    // ── TOPIC 1: ABC ───────────────────────────────────────────────────────
    {
      id: "eng_alphabet",
      title: "Алфавит ABC",
      titleKY: "ABC Алфавити",
      emoji: "🔤",
      color: "from-red-500 to-red-700",
      lightColor: "from-red-400 to-red-600",
      bgColor: "bg-red-50",
      borderColor: "border-red-300",
      subtopics: [
        {
          id: "eng_abc_am",
          title: "Буквы A – M",
          titleKY: "A – M тамгалары",
          emoji: "🅰️",
          explanation: "The English alphabet has 26 letters! First 13: A B C D E F G H I J K L M. A is for Apple 🍎, B is for Ball ⚽, C is for Cat 🐱, D is for Dog 🐶. Sing the ABC song!",
          explanationKY: "Англис алфавитинде 26 тамга бар! Алгачкы 13: A B C D E F G H I J K L M. A — Алма, B — Топ, C — Мышык.",
          tasks: [
            {
              id: 1, type: "choice",
              question: "What letter comes after A?",
              options: ["Z", "B", "C", "D"], correct: "B",
              hint: "A, B, C... B comes right after A!", emoji: "🔤",
            },
            {
              id: 2, type: "sequence",
              question: "Put the letters in the correct ABC order:",
              correctOrder: ["A", "B", "C", "D", "E"],
              hint: "A, B, C, D, E — the first five letters!", emoji: "📋",
            },
            {
              id: 3, type: "match",
              question: "Match each letter to its word:",
              pairs: [
                { left: "A", right: "Apple 🍎" },
                { left: "B", right: "Ball ⚽" },
                { left: "C", right: "Cat 🐱" },
                { left: "D", right: "Dog 🐶" },
              ],
              hint: "A for Apple, B for Ball, C for Cat, D for Dog!", emoji: "🔗",
            },
            {
              id: 4, type: "input",
              question: "Write the letter that comes after D:",
              correct: "E",
              placeholder: "One letter...",
              hint: "A, B, C, D, E — E comes after D!", emoji: "✏️",
            },
            {
              id: 5, type: "dragdrop",
              question: "Sort the letters into two groups:",
              items: [
                { label: "A", zone: "First half (A-M)" }, { label: "N", zone: "Second half (N-Z)" },
                { label: "M", zone: "First half (A-M)" }, { label: "Z", zone: "Second half (N-Z)" },
                { label: "G", zone: "First half (A-M)" }, { label: "S", zone: "Second half (N-Z)" },
              ],
              zones: ["First half (A-M)", "Second half (N-Z)"],
              hint: "A-M is the first half. N-Z is the second half of the alphabet!", emoji: "🎯",
            },
          ],
        },
        {
          id: "eng_abc_nz",
          title: "Буквы N – Z",
          titleKY: "N – Z тамгалары",
          emoji: "🔚",
          explanation: "Last 13 letters: N O P Q R S T U V W X Y Z. N is for Nose 👃, O for Orange 🍊, S for Sun ☀️, T for Tiger 🐯, Z for Zebra 🦓! Z is the last letter.",
          explanationKY: "Акыркы 13 тамга: N O P Q R S T U V W X Y Z. N — Мурун, O — Апельсин, Z — Зебра. Z — эң акыркы тамга!",
          tasks: [
            {
              id: 1, type: "choice",
              question: "What is the last letter of the English alphabet?",
              options: ["X", "Y", "Z", "W"], correct: "Z",
              hint: "Z is the 26th and last letter!", emoji: "🔚",
            },
            {
              id: 2, type: "match",
              question: "Match each letter to its word:",
              pairs: [
                { left: "N", right: "Nose 👃" },
                { left: "S", right: "Sun ☀️" },
                { left: "T", right: "Tiger 🐯" },
                { left: "Z", right: "Zebra 🦓" },
              ],
              hint: "N for Nose, S for Sun, T for Tiger, Z for Zebra!", emoji: "🔗",
            },
            {
              id: 3, type: "sequence",
              question: "Put letters in ABC order:",
              correctOrder: ["O", "P", "Q", "R", "S"],
              hint: "...N, O, P, Q, R, S, T... These come after N!", emoji: "📋",
            },
            {
              id: 4, type: "input",
              question: "Write the letter that comes after Y (last letter):",
              correct: "Z",
              placeholder: "One letter...",
              hint: "...W, X, Y, Z — Z is the very last letter!", emoji: "✏️",
            },
            {
              id: 5, type: "multi",
              question: "Select ALL letters from the second half (N-Z):",
              options: ["A", "N", "P", "C", "Z", "M"],
              correct: ["N", "P", "Z"],
              hint: "N, P, Z are all in the N-Z half. A, C, M are in A-M!", emoji: "☑️",
            },
          ],
        },
        {
          id: "eng_vowels",
          title: "Гласные и согласные",
          titleKY: "Үндүү жана үнсүз",
          emoji: "🎵",
          explanation: "In English there are 5 vowels: A, E, I, O, U. All other 21 letters are consonants. You can sing vowels: A-E-I-O-U! Every word needs a vowel!",
          explanationKY: "Англис тилинде 5 үндүү тамга бар: A, E, I, O, U. Калган 21 тамга — үнсүз. Үндүүлөрдү ырдап айтса болот!",
          tasks: [
            {
              id: 1, type: "choice",
              question: "Which letter is a vowel?",
              options: ["B", "C", "E", "D"], correct: "E",
              hint: "E is a vowel! The 5 vowels are: A, E, I, O, U", emoji: "🎵",
            },
            {
              id: 2, type: "dragdrop",
              question: "Sort the letters into vowels and consonants:",
              items: [
                { label: "A", zone: "Vowels" }, { label: "B", zone: "Consonants" },
                { label: "I", zone: "Vowels" }, { label: "K", zone: "Consonants" },
                { label: "O", zone: "Vowels" }, { label: "T", zone: "Consonants" },
              ],
              zones: ["Vowels", "Consonants"],
              hint: "Vowels: A E I O U. Everything else is a consonant!", emoji: "🎯",
            },
            {
              id: 3, type: "sequence",
              question: "Put the vowels in order:",
              correctOrder: ["A", "E", "I", "O", "U"],
              hint: "The 5 vowels in alphabetical order: A, E, I, O, U!", emoji: "📋",
            },
            {
              id: 4, type: "input",
              question: "How many vowels are in the English alphabet?",
              correct: "5",
              placeholder: "Number...",
              hint: "Count them: A, E, I, O, U — that's 5 vowels!", emoji: "🔢",
            },
            {
              id: 5, type: "multi",
              question: "Select ALL vowels:",
              options: ["A", "B", "E", "K", "U", "M"],
              correct: ["A", "E", "U"],
              hint: "Vowels are: A, E, I, O, U. Only three of these are here!", emoji: "☑️",
            },
          ],
        },
      ],
    },

    // ── TOPIC 2: First Words ───────────────────────────────────────────────
    {
      id: "eng_words",
      title: "Первые слова",
      titleKY: "Биринчи сөздөр",
      emoji: "🌈",
      color: "from-orange-500 to-orange-700",
      lightColor: "from-orange-400 to-orange-600",
      bgColor: "bg-orange-50",
      borderColor: "border-orange-300",
      subtopics: [
        {
          id: "eng_colors",
          title: "Colors — Цвета",
          titleKY: "Colors — Түстөр",
          emoji: "🎨",
          explanation: "Colours in English: Red 🔴 красный, Blue 🔵 синий, Green 🟢 зелёный, Yellow 🟡 жёлтый, White ⚪ белый, Black ⚫ чёрный, Pink 🩷 розовый.",
          explanationKY: "Англисче түстөр: Red — кызыл 🔴, Blue — көк 🔵, Green — жашыл 🟢, Yellow — сары 🟡, White — ак ⚪, Black — кара ⚫.",
          tasks: [
            {
              id: 1, type: "choice",
              question: "What colour is the sun ☀️?",
              options: ["Blue", "Green", "Yellow", "Red"], correct: "Yellow",
              hint: "The sun is Yellow! ☀️ = Yellow", emoji: "☀️",
            },
            {
              id: 2, type: "match",
              question: "Match each colour to its Russian translation:",
              pairs: [
                { left: "Red", right: "красный" },
                { left: "Blue", right: "синий" },
                { left: "Green", right: "зелёный" },
                { left: "Yellow", right: "жёлтый" },
              ],
              hint: "Red=красный, Blue=синий, Green=зелёный, Yellow=жёлтый!", emoji: "🔗",
            },
            {
              id: 3, type: "dragdrop",
              question: "Sort the colours: warm 🔥 and cool 🧊",
              items: [
                { label: "Red", zone: "Warm 🔥" }, { label: "Blue", zone: "Cool 🧊" },
                { label: "Yellow", zone: "Warm 🔥" }, { label: "Green", zone: "Cool 🧊" },
                { label: "Orange", zone: "Warm 🔥" }, { label: "White", zone: "Cool 🧊" },
              ],
              zones: ["Warm 🔥", "Cool 🧊"],
              hint: "Warm: red, yellow, orange. Cool: blue, green, white!", emoji: "🎯",
            },
            {
              id: 4, type: "input",
              question: "How do you say «белый» in English?",
              correct: "White",
              placeholder: "Colour in English...",
              hint: "White = белый ⚪ Like snow!", emoji: "❄️",
            },
            {
              id: 5, type: "sequence",
              question: "Put the colours of the rainbow in order:",
              correctOrder: ["Red", "Orange", "Yellow", "Green", "Blue"],
              hint: "Rainbow: Red, Orange, Yellow, Green, Blue, Indigo, Violet!", emoji: "🌈",
            },
          ],
        },
        {
          id: "eng_numbers",
          title: "Numbers — Числа",
          titleKY: "Numbers — Сандар",
          emoji: "🔢",
          explanation: "Numbers: One(1), Two(2), Three(3), Four(4), Five(5), Six(6), Seven(7), Eight(8), Nine(9), Ten(10). Count with me: One, Two, Three!",
          explanationKY: "Сандар: One(1), Two(2), Three(3), Four(4), Five(5), Six(6), Seven(7), Eight(8), Nine(9), Ten(10).",
          tasks: [
            {
              id: 1, type: "choice",
              question: "How do you say «5» in English?",
              options: ["Three", "Four", "Five", "Six"], correct: "Five",
              hint: "Five = 5! Count your fingers on one hand!", emoji: "🖐️",
            },
            {
              id: 2, type: "match",
              question: "Match each number word to its digit:",
              pairs: [
                { left: "Three", right: "3" },
                { left: "Seven", right: "7" },
                { left: "One", right: "1" },
                { left: "Ten", right: "10" },
              ],
              hint: "Three=3, Seven=7, One=1, Ten=10!", emoji: "🔗",
            },
            {
              id: 3, type: "sequence",
              question: "Put the number words in order (1 to 5):",
              correctOrder: ["One", "Two", "Three", "Four", "Five"],
              hint: "One, Two, Three, Four, Five — count to five!", emoji: "📋",
            },
            {
              id: 4, type: "input",
              question: "How do you say «7» in English?",
              correct: "Seven",
              placeholder: "Number word...",
              hint: "5=Five, 6=Six, 7=Seven!", emoji: "7️⃣",
            },
            {
              id: 5, type: "dragdrop",
              question: "Sort: small numbers (1-5) and big numbers (6-10):",
              items: [
                { label: "Two", zone: "Small (1-5)" }, { label: "Eight", zone: "Big (6-10)" },
                { label: "Four", zone: "Small (1-5)" }, { label: "Nine", zone: "Big (6-10)" },
                { label: "One", zone: "Small (1-5)" }, { label: "Seven", zone: "Big (6-10)" },
              ],
              zones: ["Small (1-5)", "Big (6-10)"],
              hint: "1-5: One, Two, Three, Four, Five. 6-10: Six, Seven, Eight, Nine, Ten!", emoji: "🎯",
            },
          ],
        },
        {
          id: "eng_animals",
          title: "Animals — Животные",
          titleKY: "Animals — Жаныбарлар",
          emoji: "🐾",
          explanation: "Animals: Cat 🐱 кошка, Dog 🐶 собака, Fish 🐟 рыба, Bird 🐦 птица, Horse 🐴 лошадь, Cow 🐄 корова, Bear 🐻 медведь, Lion 🦁 лев!",
          explanationKY: "Жаныбарлар: Cat — мышык 🐱, Dog — ит 🐶, Fish — балык 🐟, Bird — куш 🐦, Horse — жылкы 🐴, Cow — уй 🐄.",
          tasks: [
            {
              id: 1, type: "choice",
              question: "What is «кошка» in English?",
              options: ["Dog", "Cat", "Bird", "Fish"], correct: "Cat",
              hint: "Cat = кошка 🐱 Meow!", emoji: "🐱",
            },
            {
              id: 2, type: "match",
              question: "Match the English word to its Russian translation:",
              pairs: [
                { left: "Dog", right: "Собака 🐶" },
                { left: "Fish", right: "Рыба 🐟" },
                { left: "Bird", right: "Птица 🐦" },
                { left: "Cow", right: "Корова 🐄" },
              ],
              hint: "Dog=Собака, Fish=Рыба, Bird=Птица, Cow=Корова!", emoji: "🔗",
            },
            {
              id: 3, type: "dragdrop",
              question: "Sort animals: pets 🏠 and wild 🌲",
              items: [
                { label: "Cat", zone: "Pet 🏠" }, { label: "Lion", zone: "Wild 🌲" },
                { label: "Dog", zone: "Pet 🏠" }, { label: "Bear", zone: "Wild 🌲" },
                { label: "Fish", zone: "Pet 🏠" }, { label: "Wolf", zone: "Wild 🌲" },
              ],
              zones: ["Pet 🏠", "Wild 🌲"],
              hint: "Pets live with people. Wild animals live in nature!", emoji: "🎯",
            },
            {
              id: 4, type: "input",
              question: "How do you say «рыба» in English?",
              correct: "Fish",
              placeholder: "Animal name...",
              hint: "Fish = рыба 🐟 It swims in water!", emoji: "🐟",
            },
            {
              id: 5, type: "sequence",
              question: "Put animals in size order (smallest to biggest):",
              correctOrder: ["Fish", "Cat", "Dog", "Horse", "Elephant"],
              hint: "Fish is smallest, Elephant is biggest! Fish < Cat < Dog < Horse < Elephant", emoji: "📊",
            },
          ],
        },
      ],
    },

    // ── TOPIC 3: Greetings ────────────────────────────────────────────────
    {
      id: "eng_greetings_topic",
      title: "Знакомство и приветствие",
      titleKY: "Таанышуу жана саламдашуу",
      emoji: "👋",
      color: "from-purple-500 to-purple-700",
      lightColor: "from-purple-400 to-purple-600",
      bgColor: "bg-purple-50",
      borderColor: "border-purple-300",
      subtopics: [
        {
          id: "eng_greetings",
          title: "Hello & Goodbye",
          titleKY: "Hello & Goodbye",
          emoji: "👋",
          explanation: "«Hello!» or «Hi!» — Привет! when meeting. «Goodbye!» or «Bye!» — До свидания! when leaving. «Good morning!» — утром. «Good night!» — вечером.",
          explanationKY: "«Hello!» же «Hi!» — Салам! жолуккандa. «Goodbye!» же «Bye!» — Кош бол! кеткенде. «Good morning!» — таңертең.",
          tasks: [
            {
              id: 1, type: "choice",
              question: "How do you say «Привет» in English?",
              options: ["Goodbye", "Hello", "Sorry", "Please"], correct: "Hello",
              hint: "Hello! = Привет! We say this when we meet someone!", emoji: "👋",
            },
            {
              id: 2, type: "match",
              question: "Match the greeting to the right time/situation:",
              pairs: [
                { left: "Hello!", right: "Встречая друга" },
                { left: "Goodbye!", right: "Уходя домой" },
                { left: "Good morning!", right: "Утром" },
                { left: "Good night!", right: "Перед сном" },
              ],
              hint: "Hello=встреча, Goodbye=прощание, Morning=утро, Night=ночь!", emoji: "🔗",
            },
            {
              id: 3, type: "dragdrop",
              question: "Sort: greetings 👋 and farewells 🚶",
              items: [
                { label: "Hello", zone: "Greeting 👋" }, { label: "Bye", zone: "Farewell 🚶" },
                { label: "Hi", zone: "Greeting 👋" }, { label: "Goodbye", zone: "Farewell 🚶" },
                { label: "Good morning", zone: "Greeting 👋" }, { label: "See you", zone: "Farewell 🚶" },
              ],
              zones: ["Greeting 👋", "Farewell 🚶"],
              hint: "We greet when meeting (hello, hi). We say farewell when leaving (bye, goodbye)!", emoji: "🎯",
            },
            {
              id: 4, type: "input",
              question: "Write the short form of «Goodbye»:",
              correct: "Bye",
              placeholder: "Short word...",
              hint: "Goodbye → Bye! The short friendly version!", emoji: "✏️",
            },
            {
              id: 5, type: "sequence",
              question: "Put the conversation in the right order:",
              correctOrder: ["Hello!", "How are you?", "I am fine!", "Goodbye!"],
              hint: "First greet (Hello), then ask, then answer, then say goodbye!", emoji: "📋",
            },
          ],
        },
        {
          id: "eng_intro",
          title: "My name is...",
          titleKY: "My name is...",
          emoji: "🙋",
          explanation: "Introduce yourself: «My name is [name].» = Меня зовут. «I am [name].» = Я [имя]. To ask: «What is your name?» = Как тебя зовут? Try: My name is Aibek!",
          explanationKY: "«My name is [атың].» — Менин атым... «What is your name?» — Сенин атың ким?",
          tasks: [
            {
              id: 1, type: "choice",
              question: "How do you say «Меня зовут...» in English?",
              options: ["Your name is...", "My name is...", "His name is...", "Her name is..."], correct: "My name is...",
              hint: "MY = мой/моя. My name is... = Меня з��вут...", emoji: "🙋",
            },
            {
              id: 2, type: "sequence",
              question: "Build the introduction sentence in the right order:",
              correctOrder: ["My", "name", "is", "Aibek"],
              hint: "My name is Aibek. — Меня зовут Айбек.", emoji: "📋",
            },
            {
              id: 3, type: "match",
              question: "Match the English word to its Russian meaning:",
              pairs: [
                { left: "My", right: "Мой/Моя" },
                { left: "Name", right: "Имя" },
                { left: "I", right: "Я" },
                { left: "Your", right: "Твой/Твоя" },
              ],
              hint: "My=мой, Name=имя, I=я, Your=твой!", emoji: "🔗",
            },
            {
              id: 4, type: "input",
              question: "Complete: «My ___ is Aizat.» (What word is missing?)",
              correct: "name",
              placeholder: "Missing word...",
              hint: "My NAME is Aizat. = Меня зовут Айзат!", emoji: "✏️",
            },
            {
              id: 5, type: "dragdrop",
              question: "Sort words: about me (I/My) and about you (You/Your):",
              items: [
                { label: "I", zone: "About me" }, { label: "You", zone: "About you" },
                { label: "My", zone: "About me" }, { label: "Your", zone: "About you" },
                { label: "I am", zone: "About me" }, { label: "You are", zone: "About you" },
              ],
              zones: ["About me", "About you"],
              hint: "I, My, I am = about yourself. You, Your, You are = about the other person!", emoji: "🎯",
            },
          ],
        },
        {
          id: "eng_how_are_you",
          title: "How are you?",
          titleKY: "How are you?",
          emoji: "😊",
          explanation: "«How are you?» = Как дела? «I am fine!» = Я в порядке! «I am happy!» = Я счастлив! «I am sad» = Мне грустно. «I am tired» = Я устал.",
          explanationKY: "«How are you?» — Кандайсыз? «I am fine!» — Жакшымын! «I am happy!» — Мен бактылуумун!",
          tasks: [
            {
              id: 1, type: "choice",
              question: "What does «How are you?» mean?",
              options: ["Как тебя зовут?", "Сколько тебе лет?", "Как дела?", "Где ты?"], correct: "Как дела?",
              hint: "How are you? = Как дела? The most common question!", emoji: "❓",
            },
            {
              id: 2, type: "match",
              question: "Match the phrase to its Russian meaning:",
              pairs: [
                { left: "I am fine", right: "Я в порядке" },
                { left: "I am happy", right: "Я счастлив" },
                { left: "I am sad", right: "Мне грустно" },
                { left: "I am tired", right: "Я устал" },
              ],
              hint: "Fine=хорошо, happy=счастлив, sad=грустно, tired=устал!", emoji: "🔗",
            },
            {
              id: 3, type: "dragdrop",
              question: "Sort feelings: positive 😊 and negative 😢",
              items: [
                { label: "Happy", zone: "Positive 😊" }, { label: "Sad", zone: "Negative 😢" },
                { label: "Fine", zone: "Positive 😊" }, { label: "Tired", zone: "Negative 😢" },
                { label: "Great", zone: "Positive 😊" }, { label: "Sick", zone: "Negative 😢" },
              ],
              zones: ["Positive 😊", "Negative 😢"],
              hint: "Happy, Fine, Great = feeling good. Sad, Tired, Sick = not feeling good!", emoji: "🎯",
            },
            {
              id: 4, type: "sequence",
              question: "Build the answer: «I am fine, thank you!»",
              correctOrder: ["I", "am", "fine,", "thank", "you!"],
              hint: "I am fine, thank you! — Я в порядке, спасибо!", emoji: "📋",
            },
            {
              id: 5, type: "input",
              question: "Complete: «I ___ fine.» (What verb is missing?)",
              correct: "am",
              placeholder: "verb...",
              hint: "With I we always use AM: I am happy, I am fine!", emoji: "✏️",
            },
          ],
        },
      ],
    },
  ],
};

export function EnglishSubjectPage() {
  return <SubjectPageTemplate config={config} />;
}
